name: Conditional Sync Upstream, Build, and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  sync-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dummy step
        run: echo "Workflow ok (sync disabilitato)"
